## **Numpy** - Numerical python
**Array** - Array is an ordered collection of data points having same data type.

In [ ]:
import numpy as np

In [ ]:
# Creating numpy array

a1 = np.array([10, 20, 30, 40, 50])
print(a1)
print(type(a1))

# ndarray - n dimensional array

[10 20 30 40 50]
<class 'numpy.ndarray'>


#### Array has 4 properties
1. ndim - number of dimension
2. size - number of elements
3. dtype - data type of elemens
4. shape - shape of the array

In [ ]:
print("Array : ", a1)
print("Array Type : ", type(a1))
print("Dimension : ", a1.ndim)
print("Size : ", a1.size)
print("Data Type : ", a1.dtype)
print("Shape : ", a1.shape)

[10 20 30 40 50]
<class 'numpy.ndarray'>
1
5
int64
(5,)


In [ ]:
a2 = np.array([[12, 23, 34, 45],[56, 67, 78, 89]])
print("Array : ", a2)
print("Array Type : ", type(a2))
print("Dimension : ", a2.ndim)
print("Size : ", a2.size)
print("Data Type : ", a2.dtype)
print("Shape : ", a2.shape)  # (row, columns)

[[12 23 34 45]
 [56 67 78 89]]
<class 'numpy.ndarray'>
2
8
int64
(2, 4)


In [ ]:
a3 = np.array([[[12, 23], [34, 45]],[[56, 67], [78, 89]]])
print("Array : ", a3)
print("Array Type : ", type(a3))
print("Dimension : ", a3.ndim)
print("Size : ", a3.size)
print("Data Type : ", a3.dtype)
print("Shape : ", a3.shape)  # (3rd dimension, row, columns)

[[[12 23]
  [34 45]]

 [[56 67]
  [78 89]]]
<class 'numpy.ndarray'>
3
8
int64
(2, 2, 2)


In [ ]:
#  Using function arange

s = np.arange(5) # start=0, end=5, step=1
print(s)

[0 1 2 3 4]


In [ ]:
s = np.arange(10,40,4) # start=10, end=40, step=4
print(s)

[10 14 18 22 26 30 34 38]


In [ ]:
#  Array can be reshaped into product of it's factors


s2 = np.arange(18)
print("Array 1 : ", s2)

#  factors of 18 --> 1, 2, 3, 6, 9, 18


s2 = np.arange(18).reshape(2, 3, 3)
print("\nArray 2 : ", s2)

s2 = np.arange(18).reshape(2, 9)
print("\nArray 3 : ", s2)

Array 1 :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Array 2 :  [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

Array 3 :  [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]


In [ ]:
print(s2)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]


In [13]:
# reshaping array does not make chages to original array

#### Custom NUmpy array

In [14]:
w1 = np.ones([5,2])
print(w1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
w2 = np.zeros([4,3],dtype=int)
print(w2)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### Identity Matrix

In [19]:
w3 = np.identity(5, dtype=int)
print(w3)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


#### Linspace

In [20]:
# Generates linearly spaced element
#  Difference between any 2 consecutive pairs is constant
# start and end values are inclusive
# by default number of pairs to generate is 50

q1 = np.linspace(2, 10, 3) # start=2, end=10, number of pairs to generate=3
print(q1)

[ 2.  6. 10.]


#### **Matrix related operations**

##### **Matrix Multiplication**
1. A(p, q) and B(m, n) are multiplication compatible if q=m
2. Shape of resultant matrix will be (p, n)

In [21]:
a1 = np.arange(8).reshape(2, 4)
print(a1)

a2 = np.arange(-5, 15).reshape(4, 5)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[-5 -4 -3 -2 -1]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [24]:
r1 = np.dot(a1, a2)
print(r1.shape)
print(r1)

(2, 5)
[[ 40  46  52  58  64]
 [ 80 102 124 146 168]]


In [26]:
 print(a1)
 print("\n")
 print(a1.T)

[[0 1 2 3]
 [4 5 6 7]]


[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [27]:
r2 = a1.flatten(order = "C") # c --> Row wise flatten
print(r2)

[0 1 2 3 4 5 6 7]


In [28]:
r2 = a1.flatten(order = "F") # F --> Column wise flatten
print(r2)

[0 4 1 5 2 6 3 7]


#### Matrix multiplication element wise

In [29]:
v1 = np.arange(12).reshape(3, 4)
v2 = np.arange(-12,0).reshape(3, 4)
print(v1)
print(v2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[-12 -11 -10  -9]
 [ -8  -7  -6  -5]
 [ -4  -3  -2  -1]]


In [30]:
res = np.multiply(v1, v2)
print(res)

[[  0 -11 -20 -27]
 [-32 -35 -36 -35]
 [-32 -27 -20 -11]]


In [33]:
# Addition

print(v1 + v2)

[[-12 -10  -8  -6]
 [ -4  -2   0   2]
 [  4   6   8  10]]


In [35]:
# Concatenation

com1 = np.concatenate([v1, v2], axis=0)
print(com1)

print(v1.shape)
print(v2.shape)
print(com1.shape)

[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [-12 -11 -10  -9]
 [ -8  -7  -6  -5]
 [ -4  -3  -2  -1]]
(3, 4)
(3, 4)
(6, 4)


In [36]:
com2 = np.concatenate([v1, v2], axis=1)
print(com2)

[[  0   1   2   3 -12 -11 -10  -9]
 [  4   5   6   7  -8  -7  -6  -5]
 [  8   9  10  11  -4  -3  -2  -1]]


In [42]:
print(v1)

# sum
print("\nSum : ")
print(np.sum(v1))
print(np.sum(v1, axis=0))  # column-wise
print(np.sum(v1, axis=1))  # row-wise

# mean
print("\nMean : ")
print(np.mean(v1))
print(np.mean(v1, axis=0))  # column-wise
print(np.mean(v1, axis=1))  # row-wise

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Sum : 
66
[12 15 18 21]
[ 6 22 38]

Mean : 
5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [43]:
x1 = np.array([12, 45, 23, 67, 25, 56, 17, 19, 21])
print(x1)
print("Minimum number : ", x1.min())
print("Maximum number : ", x1.max())
print("Index of Minimum number : ", x1.argmin())
print("Index of Maximum number : ", x1.argmax())


[12 45 23 67 25 56 17 19 21]
Minimum number :  12
Maximum number :  67
Index of Minimum number :  0
Index of Maximum number :  3


In [45]:
n1 = np.random.randint(10, 40, 20).reshape(4,5)
n1

array([[26, 35, 18, 32, 29],
       [26, 24, 33, 11, 17],
       [35, 22, 19, 17, 15],
       [16, 22, 11, 28, 35]])

In [46]:
# Values along each column
print(n1.max(axis=0))
print(n1.min(axis=0))

# Values along each rows
print(n1.max(axis=1))
print(n1.min(axis=1))

[35 35 33 32 35]
[16 22 11 11 15]
[35 33 35 35]
[18 11 15 11]


In [47]:
# returns the row idx of max value for each col
print(n1.argmax(axis=0))
# returns the row idx of min value for each col
print(n1.argmin(axis=0))

# returns the col idx of max value for each row
print(n1.argmax(axis=1))
# returns the col idx of min value for each row
print(n1.argmin(axis=1))

[2 0 1 0 3]
[3 2 3 1 2]
[1 2 0 4]
[2 3 4 2]
