## **Numpy** - Numerical python
**Array** - Array is an ordered collection of data points having same data type.

In [1]:
import numpy as np

In [3]:
# Creating numpy array

a1 = np.array([10, 20, 30, 40, 50])
print(a1)
print(type(a1))

# ndarray - n dimensional array

[10 20 30 40 50]
<class 'numpy.ndarray'>


#### Array has 4 properties
1. ndim - number of dimension
2. size - number of elements
3. dtype - data type of elemens
4. shape - shape of the array

In [4]:
print("Array : ", a1)
print("Array Type : ", type(a1))
print("Dimension : ", a1.ndim)
print("Size : ", a1.size)
print("Data Type : ", a1.dtype)
print("Shape : ", a1.shape)

[10 20 30 40 50]
<class 'numpy.ndarray'>
1
5
int64
(5,)


In [5]:
a2 = np.array([[12, 23, 34, 45],[56, 67, 78, 89]])
print("Array : ", a2)
print("Array Type : ", type(a2))
print("Dimension : ", a2.ndim)
print("Size : ", a2.size)
print("Data Type : ", a2.dtype)
print("Shape : ", a2.shape)  # (row, columns)

[[12 23 34 45]
 [56 67 78 89]]
<class 'numpy.ndarray'>
2
8
int64
(2, 4)


In [6]:
a3 = np.array([[[12, 23], [34, 45]],[[56, 67], [78, 89]]])
print("Array : ", a3)
print("Array Type : ", type(a3))
print("Dimension : ", a3.ndim)
print("Size : ", a3.size)
print("Data Type : ", a3.dtype)
print("Shape : ", a3.shape)  # (3rd dimension, row, columns)

[[[12 23]
  [34 45]]

 [[56 67]
  [78 89]]]
<class 'numpy.ndarray'>
3
8
int64
(2, 2, 2)


In [7]:
#  Using function arange

s = np.arange(5) # start=0, end=5, step=1
print(s)

[0 1 2 3 4]


In [8]:
s = np.arange(10,40,4) # start=10, end=40, step=4
print(s)

[10 14 18 22 26 30 34 38]


In [11]:
#  Array can be reshaped into product of it's factors


s2 = np.arange(18)
print("Array 1 : ", s2)

#  factors of 18 --> 1, 2, 3, 6, 9, 18


s2 = np.arange(18).reshape(2, 3, 3)
print("\nArray 2 : ", s2)

s2 = np.arange(18).reshape(2, 9)
print("\nArray 3 : ", s2)

Array 1 :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Array 2 :  [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

Array 3 :  [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]


In [12]:
print(s2)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]


In [ ]:
# reshaping array does not make chages to original array